{
    "name": "CI",
    "on": {
        "push": null,
        "pull_request": null,
    },
    "jobs": {
        "hygiene": {
            "runs-on": "ubuntu-latest",
            "container": "fedora:latest",
            "steps": [
                { "uses": "actions/checkout@v2" },
                { "run": "dnf -y install python3-{mypy,flake8}" },
                { "run": "mypy --strict *.py ci/*.py" },
                { "run": "flake8 --ignore=E261,E302,E305,E731,E741" },
            ],
        },
        "el7-standalone": {
            "runs-on": "ubuntu-latest",
            "container": "centos:7",
            "steps": [
                { "uses": "actions/checkout@v2" },
                { "run": "ci/install-standalone.sh" },
                { "run": "ci/doublecheck.py" },
            ],
        },
    },
}
